version: '3.7'

services:
  fias:
    build: .
    container_name: fias
    restart: on-failure
    env_file: .env
    environment:
  #     # - MONGO_USERNAME=$MONGO_USERNAME
  #     # - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
  #     # - MONGO_DB=$MONGO_DB
    ports:
      - '1234:1234'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./dbdata:/data/db
    networks:
      - app-network
    ports:
      - '27018:27017'

networks:
  app-network:
    driver: bridge

volumes:
  # dbdata:
  node_modules:
